# Generated by Django 3.0.6 on 2020-06-20 17:22

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='机构介绍'),
        ),
    ]
