# Generated by Django 3.0.6 on 2020-07-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20200726_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='click_nums',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fav_nums',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏次数'),
        ),
    ]
