# Generated by Django 3.0.6 on 2020-06-20 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200620_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='courseresource',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='add_date',
        ),
        migrations.AddField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='video',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
