# Generated by Django 3.0.6 on 2020-06-20 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20200620_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomment',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='userask',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='add_date',
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='userask',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
